# Form implementation generated from reading ui file 'editTask.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(429, 505)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.name.setGeometry(QtCore.QRect(69, 9, 351, 132))
        self.name.setObjectName("name")
        self.deleteTaskButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deleteTaskButton.setGeometry(QtCore.QRect(210, 460, 211, 23))
        self.deleteTaskButton.setObjectName("deleteTaskButton")
        self.picture = QtWidgets.QPushButton(parent=self.centralwidget)
        self.picture.setGeometry(QtCore.QRect(69, 199, 351, 23))
        self.picture.setText("")
        self.picture.setObjectName("picture")
        self.category = QtWidgets.QComboBox(parent=self.centralwidget)
        self.category.setGeometry(QtCore.QRect(69, 173, 351, 20))
        self.category.setObjectName("category")
        self.nameLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(30, 70, 37, 16))
        self.nameLabel.setObjectName("nameLabel")
        self.categoryLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.categoryLabel.setGeometry(QtCore.QRect(9, 173, 54, 16))
        self.categoryLabel.setObjectName("categoryLabel")
        self.pictureLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.pictureLabel.setGeometry(QtCore.QRect(20, 200, 49, 16))
        self.pictureLabel.setObjectName("pictureLabel")
        self.dateLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.dateLabel.setGeometry(QtCore.QRect(40, 150, 26, 16))
        self.dateLabel.setObjectName("dateLabel")
        self.image = QtWidgets.QLabel(parent=self.centralwidget)
        self.image.setGeometry(QtCore.QRect(9, 228, 411, 221))
        self.image.setObjectName("image")
        self.date = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.date.setGeometry(QtCore.QRect(70, 150, 351, 20))
        self.date.setObjectName("date")
        self.editTaskButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.editTaskButton.setGeometry(QtCore.QRect(0, 460, 201, 23))
        self.editTaskButton.setObjectName("editTaskButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.deleteTaskButton.setText(_translate("MainWindow", "Удалить"))
        self.nameLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Задача</p></body></html>"))
        self.categoryLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Категория</p></body></html>"))
        self.pictureLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Картинка</p></body></html>"))
        self.dateLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Дата</p></body></html>"))
        self.image.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.editTaskButton.setText(_translate("MainWindow", "Изменить"))
