# Form implementation generated from reading ui file 'taskWidget.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(533, 95)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.moreInfoButton = QtWidgets.QPushButton(parent=Form)
        self.moreInfoButton.setObjectName("moreInfoButton")
        self.gridLayout.addWidget(self.moreInfoButton, 0, 1, 1, 1)
        self.task = QtWidgets.QCheckBox(parent=Form)
        self.task.setObjectName("task")
        self.gridLayout.addWidget(self.task, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.moreInfoButton.setText(_translate("Form", "Подробнее"))
        self.task.setText(_translate("Form", "CheckBox"))
